
env: TEST
server:
  http:
    addr: 127.0.0.1:7004
    timeout: 10s
    marshal:
      emitUnpopulated: true
      useProtoNames: true
  grpc:
    addr: 127.0.0.1:8004
    timeout: 10s
log:
  level: 0
  output:
    - stdout
    - file
  file:
    name: ./tmp/runtime/output.log
    maxSize: 1
    maxBackup: 5
    maxAge: 1
    compress: false
database:
  system:
    enable: true #是否启用数据库
    drive: mysql #数据库类型
    autoCreate: true #是否自动创建数据库
    connect:
      username: root
      password: root
      host: 127.0.0.1
      port: 3306
      dbName: user_center
      option: ?charset=utf8mb4&parseTime=True&loc=Local
    config:
      transformError:
        enable: true
      maxLifetime: 2h #最大生存时间
      maxOpenConn: 20 #最大连接数量
      maxIdleConn: 10 #最大空闲数量
      logLevel: 4 #日志等级
      slowThreshold: 2s #慢sql阈值
redis:
  cache:
    enable: true
    host: 127.0.0.1:6379
    username:
    password:
captcha:
  loginImage:
    type: image
    length: 6
    expire: 180s
    redis: cache
    height: 80
    width: 200
    skew: 0.7
    dotCount: 80
    refresh: true
  bindImage:
    type: image
    length: 6
    expire: 180s
    redis: cache
    height: 80
    width: 200
    skew: 0.7
    dotCount: 80
    refresh: true
  registerImage:
    type: image
    length: 6
    expire: 180s
    redis: cache
    height: 80
    width: 200
    skew: 0.7
    dotCount: 80
    refresh: true
  loginEmail:
    type: email
    length: 6
    expire: 180s
    redis: cache
    template: login
  bindEmail:
    type: email
    length: 6
    expire: 180s
    redis: cache
    template: bind
  registerEmail:
    type: email
    length: 6
    expire: 180s
    redis: cache
    template: register
loader:
  password: static/cert/password.pem
email:
  template:
    login:
      subject: 登录验证码发送通知
      path: static/template/email/default.html
      type: text/html
    bind:
      subject: 绑定验证码发送通知
      path: static/template/email/default.html
      type: text/html
    register:
      subject: 注册验证码发送通知
      path: static/template/email/default.html
      type: text/html
  user: 860808187@qq.com
  name: 青岑云
  host: smtp.qq.com
  port: 25
  password: xxx
jwt:
  redis: cache
  prefix: /user-center/admin/
  secret: limes-cloud-client-test
  expire: 2h
  renewal: 360s
  whitelist: {"GET:/user-center/client/v1/agreement":true,"GET:/user-center/client/v1/app":true,"GET:/user-center/client/v1/bind/image-captcha":true,"GET:/user-center/client/v1/login/image-captcha":true,"GET:/user-center/client/v1/register/image-captcha":true,"GET:/user-center/client/v1/register/username/check":true,"GET:/user-center/client/v1/scene":true,"POST:/user-center/client/v1/bind/email":true,"POST:/user-center/client/v1/bind/email-captcha":true,"POST:/user-center/client/v1/bind/password":true,"POST:/user-center/client/v1/login/email":true,"POST:/user-center/client/v1/login/email-captcha":true,"POST:/user-center/client/v1/login/password":true,"POST:/user-center/client/v1/register/email":true,"POST:/user-center/client/v1/register/email-captcha":true,"POST:/user-center/client/v1/register/password":true}
authentication:
  db: system
  redis: cache
  roleKey: app_keyword
  whitelist:
    GET:/user-center/client/v1/user: true
    PUT:/user-center/client/v1/user: true
business:
  service:
    resource: 127.0.0.1:8003
